name: "Main workflow"
on:
  push:
  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK env
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Set up Android SDK
        if: ${{ env.ACT }} # Only run on local act setups, as GitHub Actions provides the Android SDK on Ubuntu
        uses: android-actions/setup-android@v3

      - name: Convert line endings
        run: sed -i 's/\r$//' ./gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Gradle Cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Convert line endings
        run: sed -i 's/\r$//' ./gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Clean Project
        run: ./gradlew clean

      - name: Create Google Services JSON File
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json

      - name: Build release bundle
        run: ./gradlew assembleRelease

      - uses: filippoLeporati93/android-release-signer@v1
        name: Sign app
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.RELEASE_KEYSTORE }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}
        env:
          # override default build-tools version (33.0.0) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"


      - uses: actions/upload-artifact@v4
        name: Upload signed APK
        with:
          name: app-release-apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}